### ISSUE TITLE
Unable to use the delete option

### ISSUE THREAD

**Issue by alejandropts1** [SafeBreach-Labs/wd-pretender#11]
When i use the delete option i always receive the following error:

`C:\Users\vmtest\Downloads\wd-pretender-main\wd-pretender-main>python .\wd-pretender.py -o C:\files delete C:\users\vmtest\Desktop\file.zip

        -- Defender-Pretender: v1.0.0 (SafeBreach Labs) --

[+] Getting Signatures Location ...
[+] Definitions Path: C:\ProgramData\Microsoft\Windows Defender\Definition Updates\{09315BF8-942D-4D68-ABEB-B5412A592E1B}
[+] Loading mpasbase.vdm
[+] Loading mpasdlta.vdm
[+] Loading mpavbase.vdm
[+] Loading mpavdlta.vdm
Traceback (most recent call last):
  File "C:\Users\vmtest\Downloads\wd-pretender-main\wd-pretender-main\wd-pretender.py", line 77, in <module>
    main()
  File "C:\Users\vmtest\Downloads\wd-pretender-main\wd-pretender-main\wd-pretender.py", line 73, in main
    router(args, definitions)
  File "C:\Users\vmtest\Downloads\wd-pretender-main\wd-pretender-main\wd-pretender.py", line 31, in router
    string = base64.b64decode(args.string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Invalid base64-encoded string: number of data characters (33) cannot be 1 more than a multiple of 4`

**Comment by lilnand** [comment]
You need to provide base64 encoded string as a parameter instead of the path of the file. The string is a Defender indicator to files that contains that string to be considered as malicious

**Comment by alejandropts1** [comment]
Oh okay.

Maybe as a suggestion you could add this information in the README.md file to clarify it.

Thanks!!
